name: jwst-training-workshop

channels:
  - http://ssb.stsci.edu/astroconda

dependencies:
  - python=3.5
  - numpy>=1.6
  - scipy>=0.15
  - matplotlib>=1.3
  - astropy>=1.2.1
  - photutils>=0.2.2
  - skimage>=0.12.3
  - pandas>=0.18.1
  - glueviz>=0.9.1
  - imexam>=0.6
  - ginga>=2.5.20161005204600
